version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mongo

    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mongo:
    image: uu-app-development-docker-repo.repo.plus4u.net/uu_app_mongo_development:latest
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 5s
  rabbitmq:
    image: rabbitmq:3.8.17-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: rabbitmq
    ports:
      - 5672:5672
      - 9091:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "status"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
  gateway:
    image: uu-app-development-docker-repo.repo.plus4u.net/uu-gateway:latest
    volumes:
      - ./config/app-routes.txt:/etc/httpd/conf.d/app-routes.txt
    ports:
      - "9090:9090"
  asyncjob:
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - env_config/async-prop.env
    image: uu-app-development-docker-repo.repo.plus4u.net/uu_asyncjob_g01-server-java:latest
  businessterritory:
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - env_config/bt-prop.env
    image: uu-app-development-docker-repo.repo.plus4u.net/uu_businessterritory_maing01-server:2.21.0
  scriptEngine:
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - env_config/script-prop.env
    image: uu-app-development-docker-repo.repo.plus4u.net/uu_script_engineg02-server-nodejs:latest
  console:
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - env_config/console-prop.env
    image: uu-app-development-docker-repo.repo.plus4u.net/uu_console_maing02-server:latest
  scriptRepository:
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - env_config/script-repo-prop.env
    image: uu-app-development-docker-repo.repo.plus4u.net/uu_scriptrepository_maing02-server-nodejs:latest
  eventBroker:
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - env_config/event-prop.env
    image: uu-app-development-docker-repo.repo.plus4u.net/uu_territory_eventbrokerg01-server:latest
  myterritory:
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - env_config/mt-prop.env
    image: uu-app-development-docker-repo.repo.plus4u.net/uu_myterritory_maing01-server:latest
  digitalWorkspace:
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - env_config/dw-prop.env
    image: uu-app-development-docker-repo.repo.plus4u.net/uu_myterritory_dwg01-server-nodejs:latest
  bem:
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - env_config/bem-prop.env
    image: uu-app-development-docker-repo.repo.plus4u.net/uu_bem_maing01-server-nodejs:latest
volumes:
  mongodata:
  mongoconfig:
